/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.AffineTransform;
import javax.swing.Timer;

/**
 *
 * @author mb459
 */
public class vPanel extends javax.swing.JPanel implements ActionListener {

    
    Model model = new Model();
    Timer t = new Timer(10,this);
    
    /**
     * Creates new form vPanel
     */
    public vPanel() {
        initComponents();
        t.start();
        
                
        model.velocity = 3;
        model.theta = 3 * Math.PI / 4;
    }
    
    
    int counter = 0;
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(counter >= 1000)
            t.stop();
        model.step();
        repaint();
        counter += 10;
    }
    
    final int gridIntervalX = 1;
    final int gridIntervalY = 1;
    
    @Override
    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        AffineTransform prevTrans = g2.getTransform();
        g2.scale(getWidth() / 5, getHeight() / 5);
        
        
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2.setColor(Color.WHITE);
        g2.fillRect(0, 0, 5, 5);
        
        g2.setColor(new Color(40,40,40));
        g2.setStroke(new BasicStroke(1/5));
        for(int i = gridIntervalX; i < 5; i += gridIntervalX) {
            g2.drawLine(i, 0, i, 5);
        }
        for(int j = gridIntervalY; j < 5; j += gridIntervalY) {
            g2.drawLine(0, j, 5, j);
        }
        
        model.paint(g2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
